Feature/#12
WalkingDogWithFriends/GaeManDa pull request #17
Opened 2023-07-12 12:36 UTC by jungseokyoung-cloud

## 관련 이슈

- #12

## 작업 설명

OnBoarding화면 기초적인 UI작업 완료했습니다.

## 스크린샷
앱의 최상단인 `AppRoot` 리블렛 아래에 `LoggedOut` Viewless 리블렛을 추가했습니다.
`LoggedOut` 리블렛은 유저가 로그인 상태가 아닐 때, 제공되는 서비스들의 부모 리블렛입니다. 
ex) `SingIn`, `SingOut`,`OnBoarding`
유저가 로그인 상태는 `LoggedIn` 리블렛으로 관리하며 추후에 추가할 예정입니다. 

```mermaid
graph TD
  AppRoot --> |로그인 X|LoggedOut  
	AppRoot --> |로그인 후|LoggedIn
	LoggedOut --> OnBoarding
```

우선 `LoggedOut` Viewless리블렛 아래에 OnBoarding 리블렛을 두었습니다. 
`OnBoarding`은 ViewLess 리블렛이며, 각각 View 별로 리블렛을 가지고 있습니다. 
ex)  `TermsOfUse`, `AddressSetting` ...

### 이용약관 동의
<img src='https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/6de2ea48-e3ad-4b36-aa29-399f4c0232b6' width=200>

이용약관 동의는 눌리는 액션만 구현했습니다.

### 주소 등록 
<img src='https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/22ef7860-17f4-4a6c-b4cf-55618b9f50d2' width=200>

### 유저 설정
<img src='https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/62e9efd7-e3b5-4384-bfca-0bd941727fc0' width=200 >
<img src='https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/184b799a-df21-4dd1-97fb-1f15ee4b949b' width=200 >

### 강아지 설정

<img src='https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/e2637236-6fe4-4d61-aa07-c5051e113385' width=200>
<img src='https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/c55c6580-bc7b-4d27-addd-78e16162c2bc' width=200>
<img src='https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/bd30dd72-d290-4592-8f77-01a51fc68b7d' width=200>

강아지 설정은 DogSetting이라는 리블렛으로 3개의 리블렛을 관리합니다. 

## PR 특이 사항

- RxGesture 추가시 TermsOfUse viewcontroller의 TableView bind에서 에러가 발생합니다.
- 2번째 강아지 프로필 설정 ViewController에서 강아지 몸무게 입력하는 TextField에서 suffix(kg)까지 드래그하는 경우는 처리하지 못했습니다.
<img src='https://github.com/WalkingDogWithFriends/GaeManDa/assets/81402827/361d7132-4d97-4593-8573-5bf51fa47c6f' width=200>

2023-07-14 01:45 UTC, klmyoungyun requested changes
빌드 오류가 발생합니다 다시 확인해주세용

2023-07-14 02:46 UTC, jungseokyoung-cloud commented
> 빌드 오류가 발생합니다 다시 확인해주세용

반영완료했습니다.

2023-07-14 09:38 UTC, jungseokyoung-cloud commented
> 빌드 오류가 발생합니다 다시 확인해주세용

반영완료했습니다.

2023-07-15 04:28 UTC, klmyoungyun approved these changes
굳굳! 임포트순서만 확인하고 고치면 될듯! 고생했따

2023-07-15 04:28 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingBuilder.swift
> +
개행의 일관성이 없어보여요!

2023-07-15 04:28 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseCell/TermsOfUseCell.swift
> +import RxCocoa
알파벳 순서!

2023-07-15 04:28 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseViewController.swift
> +//	 MARK: 수정 bind -> with retained
TODO 주석인가용?

2023-07-15 04:28 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/OnBoarding/Implementations/AddressSetting/DetailAddressSetting/DetailAddressSettingViewController.swift
> +import RxCocoa
알파벳 순서!

2023-07-15 04:28 UTC, klmyoungyun commented on GaeManda/Projects/Core/GMDUtils/RxViewController.swift
> +#if os(iOS) || os(tvOS)
os 확인은 지워도 될 것 같아요

2023-07-15 04:28 UTC, klmyoungyun commented on GaeManda/Projects/Core/GMDUtils/KeyboardRespondViewController.swift
> +open class KeyboardRespondViewController: UIViewController {
파이널?

2023-07-15 04:28 UTC, klmyoungyun commented on GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
> +import RxCocoa
알파벳 순서!

2023-07-15 04:28 UTC, klmyoungyun commented
컨플릭도 처리 부탁드려용

2023-07-15 04:29 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingBuilder.swift
> +	var termsOfUseBuildable: TermsOfUseBuildable {
fileprivate로 바꿔도 상관없지 않나?

2023-07-15 05:16 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Core/GMDUtils/KeyboardRespondViewController.swift
> +open class KeyboardRespondViewController: UIViewController {
이건 키보드 반응이 필요한 경우, 
UIViewController대신 KeyboardRespondViewController를 상속하기 때문에,
final 키워드 사용이 불가능합니다.

2023-07-15 05:31 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseCell/TermsOfUseCell.swift
> +import RxCocoa
반영 완료!

2023-07-15 05:31 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/OnBoarding/Implementations/TermsOfUse/TermsOfUseViewController.swift
> +//	 MARK: 수정 bind -> with retained
삭제 했습니다.

2023-07-15 05:32 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Core/GMDUtils/RxViewController.swift
> +#if os(iOS) || os(tvOS)
반영 완료!

2023-07-15 05:32 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Core/GMDExtensions/UITextField+Extension.swift
> +import RxCocoa
반영 완료!

2023-07-15 05:32 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/OnBoarding/Implementations/OnBoardingBuilder.swift
> +	var termsOfUseBuildable: TermsOfUseBuildable {
반영 완료!

2023-07-15 06:10 UTC, jungseokyoung-cloud commented
> 컨플릭도 처리 부탁드려용

해결완료 했습니다.

2023-07-15 06:12 UTC, merged