강아지 수정 Interactor 작업
WalkingDogWithFriends/GaeManDa pull request #56
Opened 2023-08-29 16:43 UTC by jungseokyoung-cloud

## 관련 이슈

- #51

## 작업 설명
강아지 수정 Interactor 작업입니다.

## PR 특이 사항

- "수정완료"버튼 클릭 시 특정 `TextField`에 작성이 안되어있으면 warningLabel을 띄우는데, 
   해당 경우에 모든 textField를 `normal` 모드로 리셋을 하고, 작성이 안되어있는 것만 'warning'으로 변경할지, 
   혹은, 'warning'은 그대로 두고, 새롭게 만족 안한것들을 추가적으로 'warning'으로 변경할지 상의해야할것 같습니다.

2023-08-31 15:55 UTC, klmyoungyun requested changes
키보드 계산이 잘못된 것 같아. 아래 사진 봐죠
키보드 계산 고치는데 혹시 코드들이 수정될 수 있으니 고치면 리뷰 다시 시작할겜

|숫자키보드라서 리턴키로도 내리질 못함|아래 완료 버튼이 안 보임|
|:---:|:---:|
|![Simulator Screen Recording - iPhone 13 mini - 2023-09-01 at 00 50 04](https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/fc9009e6-a8de-4f53-830c-bf2fb5b43e43)|![Simulator Screen Recording - iPhone 13 mini - 2023-09-01 at 00 49 54](https://github.com/WalkingDogWithFriends/GaeManDa/assets/48887389/5ab6f904-3e66-415d-a3aa-68e31b9d7222)|

+)그리구 바깥 영역을 선택하면 키보드가 안 내려가..!

2023-08-31 15:55 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +	}
하이!!!!!!! 구독 할 때 하는 게 많넹 업데이트 시 발생하는 로직을 전부 subscribe안에 작성해서 그런 것같아!! 어떻게 해결할 수 있을까!? (궁금하면 카톡~)

2023-08-31 15:55 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditViewController.swift
> +		dogProfileDashBoard.rx.setDelegate(self).disposed(by: disposeBag)
ui관련된게 아닌거같은데!?

2023-09-01 03:12 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +				.subscribe(with: self) { owner, result in
이건 서버로 post요청하는 거여서 main에서 일어날 필요 없지 않아?

2023-09-03 05:23 UTC, klmyoungyun requested changes

2023-09-03 05:23 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +import RxCocoa
순서 ㅎㅎ

2023-09-03 05:23 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +	func updateDogDashBoard(doges: [DogDashBoardViewModel])
매개변수의 타입이 도그대쉬보드를 나타내는거같은데 매개변수명이 도그즈는 어색한거같아ㅇㅅㅇ

2023-09-03 05:23 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +			.skip(1)
skip은 무슨 역할이양?

2023-09-03 05:23 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +		let combineObservable = Observable.combineLatest(editDogId, dogs)
공유해주세용~~ 여러곳에서 쓰이네용

2023-09-03 05:23 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +	private let editDogId = BehaviorRelay<Int>(value: 0)
0은 의미가 있는 `editDogid` 값인가?!
만약 의미 없는 값이라면 선언만하고 초기화 단계에서 생성해주는것은 어때?!

2023-09-03 08:17 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +import RxCocoa
반영 완료!

2023-09-03 08:18 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +		let combineObservable = Observable.combineLatest(editDogId, dogs)
반영 완료!

2023-09-03 08:18 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +	private let editDogId = BehaviorRelay<Int>(value: 0)
반영 완료!

2023-09-03 08:29 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +	func updateDogDashBoard(doges: [DogDashBoardViewModel])
반영완료!

2023-09-03 08:33 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +			.skip(1)
이건 이제 없어도 될꺼같아 나중에 설명해줄게

2023-09-03 09:22 UTC, klmyoungyun approved these changes
하나만 확인하면 될듯?! 굳굳 수정하고 머지해죠!!

2023-09-03 09:22 UTC, klmyoungyun commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +				owner.presenter.updateDogDashBoard(dogViewModels: viewModel)
요거 넘어오는 파라미터도 수정해주셔야ㅐ해용~~~!!

2023-09-03 12:00 UTC, jungseokyoung-cloud commented on GaeManda/Projects/Presentation/GMDProfile/Implementations/DogProfileEdit/DogProfileEditInteractor.swift
> +				owner.presenter.updateDogDashBoard(dogViewModels: viewModel)
수정한건데여??

2023-09-03 14:22 UTC, merged